version: '3'

networks:
  broker:


services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    user: "0:0"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - broker
    volumes:
      - ./broker/zookeeper/data:/var/lib/zookeeper/data
      - ./broker/zookeeper/log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    user: "0:0"
    depends_on:
      - zookeeper
    networks:
      - broker
    ports:
      - 9092:9092
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
    volumes:
      - ./broker/kafka/data:/var/lib/kafka/data

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    depends_on:
      - kafka
    networks:
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
